### ISSUE TITLE
intword() approx vs. exact

### ISSUE THREAD

**Issue by theleoji** [rdmurphy/journalize#101]
Would it be worthwhile to extend `intword()` so that it indicates whether the result is exact (65000000 = 6.5 million, EXACT) versus rounded (65036204 = 6.5 million, APPROX)?

**Comment by rdmurphy** [comment]
Hey @theleoji!

I've given this some thought, and I think it may be a little out of scope for `journalize`. The basic contract here is that you insert a single value and get a string in return. It'd be a big change if we had to switch to something like an object so we could encode extra information!

But it did get me thinking about ways you could do this independently of `intword`. 🤔 Then `intword` could just be used for the formatting of the string and combined with some other method of determining exactness. Maybe there's an algorithm out there that can figure that out cleanly?

Thanks for the suggestion!
