### ISSUE TITLE
[feat] Ordinal parameter to return only suffix

### ISSUE THREAD

**Issue by sawyerclick** [rdmurphy/journalize#283]
**What**
Add an optional parameter to have `journalize.ordinal()` return solely the suffix. Alternatively, add parameters to return it wrapped in `sup` or `sub` (though this assumption is not ideal).

I'm willing to write a quick PR for this.

**Why**
In many cases I would like to style or otherwise display the suffix. This currently is not possible without evoking the function, running code to split numbers from letters, and then rendering the html. It'd be easier and less expensive to have journalize break it apart for me.

Example use case:

```html
<p>1<sup>st</sup></p>
```

**How**

Add an `onlySuffix` param in the default function of `src/ordinal.js`:

```js
// if `convertedVal` is 11, 12 or 13, English gets weird
if (ENGLISH_ORDINAL_EXCEPTIONS.indexOf(convertedVal % 100) > -1) {
  if (onlySuffix) return SUFFIXES[0];
  return convertedVal + SUFFIXES[0];
}

if (onlySuffix) return SUFFIXES[convertedVal % 10];
return convertedVal + SUFFIXES[convertedVal % 10];
```

With an additional parameter, it may be best to have the parameters now be in object form for clarity. This would be a breaking change though.

```js
journalize.ordinal(num, { spellOutOrdinal: boolean, onlySuffix: boolean })
```

**Comment by sawyerclick** [comment]
It would also involve some logic to check that `spellOutOrdinals` and `onlySuffix` are not simultaneously true. With the example code above, though, `spellOutOrdinals` takes precedence, as it is originally written.

**Comment by rdmurphy** [comment]
Hey @sawyerclick — I think this is a great idea!

For better or worse I've been pretty consistent about not having the methods of `journalize` have extra parameters and I would like to keep it that way if possible. What do you think about instead adding this functionality as a new function? Perhaps `journalize.ordinalsuffix()`?

Then we could make `ordinal` use that for the actual suffix logic and surface both paths without a breaking change.

**Comment by sawyerclick** [comment]
That works swell! I'm happy to take the first bite at creating this, unless you have a hankering for it.

`ordinalSuffix` would reuse the same arrays you have up top, so we could move those to a shared file. I see the final being something like this, following _a lot_ of the smart logic in the original:

```js
// `ordinals` here represents an object in
// which we can store the shared arrays/logic
// between ordinal and ordinalSuffix
import { isInteger, isNil, ordinals } from './utils';

export default function ordinalSuffix(val) {
  // if `val` is undefined or null, return an empty string
  if (isNil(val)) return '';

  const convertedVal = +val;

  // if `convertedVal` is not an integer, return `val`
  if (!isInteger(convertedVal)) return '';

  // if `convertedVal` is 11, 12 or 13, English gets weird
  if (ENGLISH_ORDINAL_EXCEPTIONS.indexOf(convertedVal % 100) > -1) {
    return SUFFIXES[0];
  }

  return SUFFIXES[convertedVal % 10];
}

```

**Comment by sawyerclick** [comment]
After some thought, I wonder if it's worth the extra bytes in being its own function or existing outside of `ordinal.js`. The suffix can essentially be accessed via `ordinal(12).slice(-2)`, and the param was merely a convenience. I'm torn between "yes! this should exist to make it easier" and "no! that's convenience at the sake of bloat and overhead. something native exists!"

**Comment by rdmurphy** [comment]
Hah yeah know what you mean! 😅 

[I gave it a pass](https://github.com/rdmurphy/journalize/tree/feature-ordinal-suffix) and honestly I think it's fine! This isn't really adding all that many extra bytes other than the additional export of `ordinalsuffix`. I didn't add much new code to pull it off — I [extracted the suffix stuff out of `ordinal`](https://github.com/rdmurphy/journalize/blob/feature-ordinal-suffix/src/ordinalsuffix.js) and now [`ordinal` uses `ordinalsuffix` internally](https://github.com/rdmurphy/journalize/blob/03eba4bfd26736ca20b52cb77fcadf950f85d0f4/src/ordinal.js#L61-L62).
