### ISSUE TITLE
aptime gives incorrect output at noon

### ISSUE THREAD

**Issue by jmuyskens** [rdmurphy/journalize#95]
The hour is reported as 0 rather than 12.

```
var journalize = require("journalize")
var date = new Date("2018-09-15T16:39:27.832Z") // My browser is in Eastern time
journalize.aptime(date) // "0:39 p.m."
```

I reproduced this bug in Chrome 68 and Firefox 62 running on macOS Sierra.

**Comment by rdmurphy** [comment]
@jmuyskens Thanks for the heads up! Could have swore I caught that pre-2.0.0, but it appears not. Just published the fix in `2.0.1`.
